INSERT INTO tb_category(name) VALUES ('Livros');
INSERT INTO tb_category(name) VALUES ('Eletrônicos');
INSERT INTO tb_category(name) VALUES ('Computadores');

INSERT INTO tb_product (name, price, description, img_url) VALUES ('O Senhor dos Anéis', 90.5, 'Clássico da literatura fantástica escrito por J.R.R. Tolkien, narrando a jornada épica para destruir o Um Anel.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Samsung Crystal UHD 55"', 2190.0, 'Smart TV com tela 4K, tecnologia HDR e acesso a aplicativos de streaming como Netflix e YouTube.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/2-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Apple MacBook Pro M1', 1250.0, 'Notebook da Apple com chip M1, tela Retina e excelente desempenho para tarefas profissionais.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/3-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Dell G15 Ryzen Edition', 1200.0, 'Notebook gamer com processador AMD Ryzen e placa de vídeo dedicada para alto desempenho em jogos.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/4-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Ruby on Rails para Leigos', 100.99, 'Guia introdutório para aprender desenvolvimento web com Ruby on Rails de forma simples e objetiva.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/5-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Acer Nitro 5', 1350.0, 'Notebook gamer com excelente custo-benefício, ideal para jogos e multitarefas.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/6-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Lenovo Legion 5', 1350.0, 'Notebook gamer com ótimo desempenho gráfico e sistema de resfriamento eficiente.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/7-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('PC Gamer Alpha', 1850.0, 'Computador montado com processador Intel i5, 16GB RAM e GTX 1660, pronto para jogos e streaming.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/8-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('PC Gamer Tera X', 1950.0, 'Setup gamer com gabinete RGB, SSD de 512GB e alto desempenho para jogos AAA.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/9-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('PC Gamer Y40', 1700.0, 'PC ideal para gamers iniciantes, com ótima performance e boa refrigeração.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/10-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('PC Gamer Nitro 5X', 1450.0, 'Computador de entrada com ótimo custo-benefício para jogos competitivos.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/11-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('PC Gamer Radeon RX', 1850.0, 'Equipado com placa de vídeo AMD RX 6600, ideal para jogos em Full HD.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/12-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('PC Gamer Plus GTX', 1350.0, 'PC intermediário com placa GTX 1650, ideal para eSports e produtividade.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/13-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('PC Gamer Hera RTX', 2250.0, 'Máquina equipada com RTX 3060, 32GB de RAM e SSD NVMe, performance premium.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/14-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('PC Gamer Weed Pro', 2200.0, 'Setup com processador Intel i7, ideal para jogos, edição de vídeo e multitarefa.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/15-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('PC Gamer MaxPower', 2340.0, 'PC de alto desempenho com refrigeramento líquido e overclock de fábrica.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/16-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('PC Gamer Turbo X', 1280.0, 'Máquina rápida e silenciosa para jogadores casuais e streamers.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/17-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('PC Gamer HotFire', 1450.0, 'Com gabinete com iluminação RGB e hardware potente para games atuais.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/18-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('PC Gamer EZ Pro', 1750.0, 'Computador ideal para streamers e editores, com ótimo custo-benefício.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/19-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('PC Gamer TRX', 1650.0, 'Com placa dedicada e processador de última geração para jogos e design.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/20-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('PC Gamer TX Pro', 1680.0, 'Build confiável para quem busca performance em multitarefa e jogos.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/21-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('PC Gamer ER Advanced', 1850.0, 'Ideal para criadores de conteúdo e jogos com gráficos intensos.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/22-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('PC Gamer Mini X', 2250.0, 'Compacto e poderoso, perfeito para setups minimalistas.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/23-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('PC Gamer Boost', 2350.0, 'Com SSD ultra-rápido e 32GB RAM, perfeito para produtividade e jogos.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/24-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('PC Gamer FullForce', 4170.0, 'Máquina de alto desempenho com hardware premium para entusiastas.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/25-big.jpg');

INSERT INTO tb_product_category (product_id, category_id) VALUES (1, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (2, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (2, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (3, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (4, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (5, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (6, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (7, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (8, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (9, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (10, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (11, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (12, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (13, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (14, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (15, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (16, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (17, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (18, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (19, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (20, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (21, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (22, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (23, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (24, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (25, 3);

INSERT INTO tb_user (name, email, phone, password, birth_date) VALUES ('Maria Brown', 'maria@gmail.com', '988888888', '123456', '2001-07-25');
INSERT INTO tb_user (name, email, phone, password, birth_date) VALUES ('Alex Green', 'alex@gmail.com', '977777777', '123456', '1987-12-13');

INSERT INTO tb_order (moment, status, client_id) VALUES (TIMESTAMP WITH TIME ZONE '2022-07-25T13:00:00Z', 1, 1);
INSERT INTO tb_order (moment, status, client_id) VALUES (TIMESTAMP WITH TIME ZONE '2022-07-29T15:50:00Z', 3, 2);
INSERT INTO tb_order (moment, status, client_id) VALUES (TIMESTAMP WITH TIME ZONE '2022-08-03T14:20:00Z', 0, 1);

INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (1, 1, 2, 90.5);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (1, 3, 1, 1250.0);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (2, 3, 1, 1250.0);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (3, 1, 1, 90.5);

INSERT INTO tb_payment (order_id, moment) VALUES (1, TIMESTAMP WITH TIME ZONE '2022-07-25T15:00:00Z');
INSERT INTO tb_payment (order_id, moment) VALUES (2, TIMESTAMP WITH TIME ZONE '2022-07-30T11:00:00Z');